# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_question_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='readingpassage',
            new_name='reading_rea_jlpt_le_173583_idx',
            old_name='reading_pas_jlpt_le_3f2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='readingpassage',
            new_name='reading_rea_title_37f3a6_idx',
            old_name='reading_pas_title_08b644_idx',
        ),
        migrations.RenameIndex(
            model_name='readingquestion',
            new_name='reading_rea_passage_656901_idx',
            old_name='reading_que_passage_72e47f_idx',
        ),
        migrations.RenameIndex(
            model_name='readingquestion',
            new_name='reading_rea_questio_e43557_idx',
            old_name='reading_que_question_41b4fd_idx',
        ),
    ]
