# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='tracking_us_user_id_78620b_idx',
            old_name='tracking_use_user_id_34f706_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogress',
            new_name='tracking_us_user_id_852432_idx',
            old_name='tracking_use_user_id_6f86b4_idx',
        ),
    ]
