"""Claude-powered JLPT exam question generator."""
from __future__ import annotations

import json
import logging

from django.conf import settings
from django.db import transaction

from .models import ExamOption, ExamQuestion, JLPTExam

logger = logging.getLogger(__name__)

SECTION_COUNTS = {
    "vocabulary": 25,
    "grammar": 20,
    "reading": 15,
    "full": 60,
}

SYSTEM_PROMPT = """You are an expert JLPT exam writer. Generate authentic JLPT practice questions.
Return ONLY a valid JSON object — no markdown, no code fences.

JSON shape:
{
  "title": "<descriptive exam title>",
  "questions": [
    {
      "section": "vocabulary" | "grammar" | "reading",
      "question_type": "multiple_choice",
      "question_text": "<question in Japanese with English context if needed>",
      "passage_text": "<reading passage — empty string for vocab/grammar>",
      "options": [
        {"label": "A", "text": "<option text>", "is_correct": false},
        {"label": "B", "text": "<option text>", "is_correct": true},
        {"label": "C", "text": "<option text>", "is_correct": false},
        {"label": "D", "text": "<option text>", "is_correct": false}
      ],
      "explanation": "<why the correct answer is correct, in English>"
    }
  ]
}

Rules:
- Exactly ONE option must have is_correct: true per question
- questions array must have exactly the requested count
- All content must be appropriate for the specified JLPT level
- Vocabulary questions test word meaning, reading, or usage in context
- Grammar questions test sentence patterns appropriate to the JLPT level
- Reading questions must include passage_text (at least 80 characters of Japanese)
- Distractors must be plausible — never obviously wrong
- Return ONLY the JSON object"""


def _get_client():
    api_key = getattr(settings, "ANTHROPIC_API_KEY", "") or ""
    if not api_key:
        return None
    try:
        import anthropic
        return anthropic.Anthropic(api_key=api_key)
    except ImportError:
        return None


def _parse_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        text = "\n".join(l for l in lines if not l.strip().startswith("```")).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start != -1 and end != -1:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                pass
    return {}


@transaction.atomic
def generate_exam(level: str, section: str, user) -> JLPTExam:
    """Call Claude and persist a full exam. Returns the saved JLPTExam."""
    client = _get_client()
    if client is None:
        raise RuntimeError("anthropic package not installed or ANTHROPIC_API_KEY not set.")

    count = SECTION_COUNTS.get(section, 20)
    section_label = section if section != "full" else "vocabulary, grammar, and reading (mix evenly)"

    user_msg = (
        f"Generate {count} {level} JLPT practice questions for the '{section_label}' section.\n"
        f"Target level: {level} (vocabulary and grammar appropriate for {level}).\n"
        f"Return exactly {count} questions in the JSON format specified."
    )

    model = getattr(settings, "ANTHROPIC_MODEL", "claude-haiku-4-5-20251001")
    try:
        import anthropic
        message = client.messages.create(
            model=model,
            max_tokens=8000,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_msg}],
        )
    except Exception as exc:
        logger.error("AI exam generation error: %s", exc)
        raise RuntimeError(f"Claude API error: {exc}") from exc

    raw = message.content[0].text if message.content else "{}"
    data = _parse_json(raw)

    if not data or "questions" not in data:
        raise ValueError("AI returned unexpected format — no 'questions' key.")

    questions_data = data["questions"]
    if not questions_data:
        raise ValueError("AI returned 0 questions.")

    # Map section to JLPTExam.SectionType
    section_type_map = {
        "vocabulary": JLPTExam.SectionType.LANGUAGE_KNOWLEDGE,
        "grammar": JLPTExam.SectionType.LANGUAGE_KNOWLEDGE,
        "reading": JLPTExam.SectionType.READING,
        "full": JLPTExam.SectionType.FULL,
    }
    duration_map = {"vocabulary": 35, "grammar": 35, "reading": 60, "full": 105}

    title = data.get("title") or f"AI-Generated {level} {section.capitalize()} Practice"
    exam = JLPTExam.objects.create(
        level=level,
        title=title,
        description=f"Auto-generated by Claude AI — {count} questions at {level} level.",
        section_type=section_type_map.get(section, JLPTExam.SectionType.FULL),
        duration_minutes=duration_map.get(section, 60),
        is_official_style=False,
        is_published=True,
        created_by=user,
    )

    for order, q in enumerate(questions_data):
        question = ExamQuestion.objects.create(
            exam=exam,
            order=order,
            section=q.get("section", "vocabulary"),
            question_type=q.get("question_type", "multiple_choice"),
            question_text=q.get("question_text", ""),
            passage_text=q.get("passage_text", ""),
            explanation=q.get("explanation", ""),
            points=1,
        )
        for opt in q.get("options", []):
            ExamOption.objects.create(
                question=question,
                label=opt.get("label", "A"),
                text=opt.get("text", ""),
                is_correct=bool(opt.get("is_correct", False)),
            )

    return exam
