# Generated by Django 4.2.30 on 2026-05-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('deck_type', models.CharField(choices=[('kanji', 'Kanji'), ('vocab', 'Vocabulary'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N2', max_length=2)),
                ('system_key', models.CharField(blank=True, default='', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('srs_algo', models.CharField(choices=[('sm2', 'SM-2 (Anki-style)'), ('fsrs', 'FSRS-4.5')], default='sm2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('suspended', models.BooleanField(default=False)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_rating', models.CharField(blank=True, max_length=10)),
                ('fsrs_stability', models.FloatField(blank=True, null=True)),
                ('fsrs_difficulty', models.FloatField(blank=True, null=True)),
                ('fsrs_state', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.deck')),
                ('kanji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flash_cards', to='content.kanji')),
                ('vocab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flash_cards', to='content.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('kanji', 'Kanji'), ('vocab', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening'), ('flashcard', 'Flashcard')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['user', '-imported_at'], name='flashcards__user_id_2450c1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'deck_type'], name='flashcards__user_id_6efd11_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'jlpt_level'], name='flashcards__user_id_61bc86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'due_at'], name='flashcards__deck_id_616d58_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'suspended'], name='flashcards__deck_id_f98a1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'kanji'), name='uniq_card_deck_kanji'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'vocab'), name='uniq_card_deck_vocab'),
        ),
    ]
