# Generated by Django 5.2.12 on 2026-04-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='card',
            new_name='flashcards__deck_id_616d58_idx',
            old_name='flashcards_c_deck_id_73eb1c_idx',
        ),
        migrations.RenameIndex(
            model_name='card',
            new_name='flashcards__deck_id_f98a1c_idx',
            old_name='flashcards_c_deck_id_62f114_idx',
        ),
        migrations.RenameIndex(
            model_name='deck',
            new_name='flashcards__user_id_6efd11_idx',
            old_name='flashcards_d_user_id_4fb0d2_idx',
        ),
        migrations.RenameIndex(
            model_name='deck',
            new_name='flashcards__user_id_61bc86_idx',
            old_name='flashcards_d_user_id_3dcfbb_idx',
        ),
    ]
