# Generated by Django 5.2.13 on 2026-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_locked_default_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fsrs_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fsrs_stability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fsrs_state',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='deck',
            name='srs_algo',
            field=models.CharField(choices=[('sm2', 'SM-2 (Anki-style)'), ('fsrs', 'FSRS-4.5')], default='sm2', max_length=10),
        ),
    ]
