# Generated by Django 4.2.30 on 2026-05-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_type', models.CharField(choices=[('balanced', 'Balanced'), ('focus_support', 'Focus Support'), ('calm_structure', 'Calm Structure')], default='balanced', max_length=24)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N2', max_length=2)),
                ('daily_goal_new_items', models.PositiveIntegerField(default=20)),
                ('session_minutes_preference', models.PositiveIntegerField(default=10)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_interval_minutes', models.PositiveIntegerField(default=25)),
                ('ui_prefs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppearanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=12)),
                ('font_family', models.CharField(choices=[('sans', 'Sans'), ('serif', 'Serif'), ('rounded', 'Rounded'), ('mono', 'Mono')], default='sans', max_length=16)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=12)),
                ('font_weight', models.CharField(choices=[('light', 'Light'), ('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=12)),
                ('font_color', models.CharField(default='#f5f7fb', max_length=16)),
                ('background_type', models.CharField(choices=[('color', 'Solid color'), ('gradient', 'Gradient'), ('image', 'Image')], default='gradient', max_length=12)),
                ('background_value', models.JSONField(blank=True, default=dict)),
                ('blur_level', models.PositiveSmallIntegerField(default=0)),
                ('opacity', models.FloatField(default=1.0)),
                ('border_radius', models.PositiveSmallIntegerField(default=14)),
                ('shadow_level', models.PositiveSmallIntegerField(default=2)),
                ('animation_level', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=12)),
                ('layout_density', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('spacious', 'Spacious')], default='comfortable', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_type', models.CharField(choices=[('daruma', 'Daruma'), ('maneki', 'Maneki'), ('kitsune', 'Kitsune'), ('tanuki', 'Tanuki')], default='daruma', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_companion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
