# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vocabulary',
            new_name='content_voc_jlpt_le_8359ae_idx',
            old_name='content_voc_jlpt_le_6f95d7_idx',
        ),
        migrations.RenameIndex(
            model_name='vocabulary',
            new_name='content_voc_word_1a5dd8_idx',
            old_name='content_voc_word_4d8a8e_idx',
        ),
    ]
