# Generated by Django 5.2.13 on 2026-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_content_voc_jlpt_le_6f95d7_idx_content_voc_jlpt_le_8359ae_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='frequency_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Lower = more common (1 = most frequent)', null=True),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['frequency_rank'], name='content_voc_frequen_5a09d0_idx'),
        ),
    ]
