# Generated by Django 4.2.30 on 2026-05-01 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('scale', 'Scale'), ('mcq', 'Multiple choice')], default='scale', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trait_key', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserNeuroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('balanced', 'Balanced learner'), ('quick_reset', 'Quick Reset learner'), ('focus_support', 'Focus Support learner'), ('momentum_support', 'Momentum Support learner'), ('calm_structure', 'Calm Structure learner')], max_length=32)),
                ('trait_scores', models.JSONField(default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180)),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('weight_mapping', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='neuro.neuroquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserNeuroAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField(default=dict)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuro.neuroquestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='neuro.neurooption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neuro_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'question'], name='neuro_usern_user_id_0f0609_idx'), models.Index(fields=['user', 'answered_at'], name='neuro_usern_user_id_0988ea_idx')],
            },
        ),
    ]
