# Generated by Django 5.2.13 on 2026-04-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuro', '0002_neutral_result_type_values'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userneuroanswer',
            new_name='neuro_usern_user_id_0f0609_idx',
            old_name='neuro_usern_user_id_f2a1b3_idx',
        ),
        migrations.RenameIndex(
            model_name='userneuroanswer',
            new_name='neuro_usern_user_id_0988ea_idx',
            old_name='neuro_usern_user_id_597de2_idx',
        ),
    ]
