# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_user_id_0af6b9_idx',
            old_name='notes_note_user_id_1f8baf_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_note_user_id_e35bbb_idx',
            old_name='notes_note_user_id_4b0f7d_idx',
        ),
    ]
