# Generated by Django 4.2.30 on 2026-05-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N2', max_length=2)),
                ('section', models.CharField(choices=[('bunpo_form', '文法形式の判断'), ('sentence_build', '文の組み立て'), ('text_grammar', '文章の文法'), ('other', 'Other')], default='other', max_length=30)),
                ('question_type', models.CharField(choices=[('choose', 'Choose best'), ('fill_blank', 'Fill blank'), ('reorder', 'Reorder'), ('error_find', 'Find error'), ('other', 'Other')], default='choose', max_length=30)),
                ('context_text_jp', models.TextField(blank=True)),
                ('prompt', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['jlpt_level', 'section'], name='grammar_gra_jlpt_le_c5871b_idx'), models.Index(fields=['jlpt_level', 'question_type'], name='grammar_gra_jlpt_le_e64049_idx')],
            },
        ),
    ]
