# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='grammarquestion',
            new_name='grammar_gra_jlpt_le_c5871b_idx',
            old_name='grammar_que_jlpt_le_f93b6b_idx',
        ),
        migrations.RenameIndex(
            model_name='grammarquestion',
            new_name='grammar_gra_jlpt_le_e64049_idx',
            old_name='grammar_que_jlpt_le_1903e2_idx',
        ),
    ]
