# Generated by Django 4.2.30 on 2026-05-01 23:26

import apps.listening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=apps.listening.models.listening_audio_path)),
                ('audio_filename', models.CharField(blank=True, max_length=255)),
                ('section', models.CharField(choices=[('kadai', '課題理解'), ('point', 'ポイント理解'), ('gaiyo', '概要理解'), ('sokuji', '即時応答'), ('togo', '統合理解'), ('other', 'Other')], default='other', max_length=20)),
                ('question_type', models.CharField(choices=[('gist', 'Main idea (gist)'), ('detail', 'Details'), ('inference', 'Inference'), ('purpose', 'Purpose'), ('response', 'Response'), ('other', 'Other')], default='other', max_length=20)),
                ('audio_text', models.TextField(blank=True)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='N2', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['jlpt_level'], name='listening_l_jlpt_le_dfc78d_idx'), models.Index(fields=['jlpt_level', 'section'], name='listening_l_jlpt_le_bded3e_idx'), models.Index(fields=['jlpt_level', 'question_type'], name='listening_l_jlpt_le_31d4d1_idx')],
            },
        ),
    ]
