# Generated by Django 5.2.12 on 2026-04-09 09:04

import apps.listening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0003_question_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listeningquestion',
            new_name='listening_l_jlpt_le_dfc78d_idx',
            old_name='listening_l_jlpt_le_b5c873_idx',
        ),
        migrations.RenameIndex(
            model_name='listeningquestion',
            new_name='listening_l_jlpt_le_bded3e_idx',
            old_name='listening_l_jlpt_se_6d52f9_idx',
        ),
        migrations.RenameIndex(
            model_name='listeningquestion',
            new_name='listening_l_jlpt_le_31d4d1_idx',
            old_name='listening_q_jlpt_le_25e28e_idx',
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.listening.models.listening_audio_path),
        ),
    ]
