# Generated by Django 5.2.12 on 2026-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testquestion',
            new_name='assessment__test_id_e8d51e_idx',
            old_name='assessment_t_test_id_47a4a3_idx',
        ),
    ]
